### ISSUE TITLE
DOC: examples

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#14]
This section of the documentation is too minimal IMO, and its' a section that users will be likely to visit.

Generally, the same comments I made in https://github.com/LMBooth/pybci/issues/10 also apply here, i.e. what does a user have to do to get any individual example running? Just linking them to an online script does not provide an intuitive user experiencing.

In addition:
- The table does not seem like a good way to represent the different examples, I had to scroll horizontally in order to be able to read each paragraph. I suggest putting all examples into their own subsection
- You could consider adding a tag (e.g. using https://shields.io/) to each example that shows whether it can be used with the pseudodevice or not. If this is useful, then these tags can be used for other categorizations of examples as well.

Regarding the statement:
> if using with own LSL capable hardware you may need to adjust the scripts accordingly, namely set createPseudoDevice=False.

I think it's suboptimal if users have to change scripts in order to make examples work. I think passing an argument to the script itself would make it easier for them. This is another indication that a command line API would be useful (see https://github.com/LMBooth/pybci/issues/12).

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Note to self: add documentation for cli commands

**Comment by LMBooth** [comment]
Hi @jsheunis, thanks for pointing out these recommendations. I've amended the hard to navigate table and added shields and more informative text describing what is needed to get the user to understand how to use the examples.

In regard to arg passing for the examples - I've now implemented a few [CLI based examples](https://github.com/LMBooth/pybci/tree/main/pybci/CliTests)  where arguments can be passed. For the [example scripts here](https://github.com/LMBooth/pybci/tree/main/pybci/Examples) my intention is to make it simple for people to take the scripts, edit and implement their own use cases as needed. Since CLI based examples are available i feel adding argument parsing to the other examples will increase the cognitive workload to deduce what is necessary or not. Would you agree that with the addition of the CLI examples the addition of arg passing to the other examples is no longer needed and makes them clearer to read and understand?

**Comment by jsheunis** [comment]
> Since CLI based examples are available i feel adding argument parsing to the other examples will increase the cognitive workload to deduce what is necessary or not. Would you agree that with the addition of the CLI examples the addition of arg passing to the other examples is no longer needed and makes them clearer to read and understand?

Yes I agree 👍
