### ISSUE TITLE
JOSS: several paper comments

### ISSUE THREAD

**Issue by jsheunis** [LMBooth/pybci#5]
- The summary section states "integration into other systems..." - which other systems, could this statement be a bit more specific?
- The software functionality section states "end-to-end solution for BCI research" but also ""no additional visualization...". These statements seem contradictory, since I would think an end to end solution includes everything one needs to conduct the research. Relatedly, the paper states researchers can focus on their experiments and don't need extensive software development skills. If they have to integrate it with visualization tools or other systems in order to have the whole system function correctly, this statement might not be completely true.

Ping https://github.com/openjournals/joss-reviews/issues/5706

**Comment by LMBooth** [comment]
Hi @jsheunis ,

To avoid me being to vague in the first point, i've reduced it from the previous to:
"PyBCI puts emphasis on quick and easy customisation of applied time-series feature extraction techniques, applied machine learning models, and live data classification." I think the point i was trying to get at is that it can be integrated in to larger python projects, but i feel its a non sequitur for where i've placed it - Hopefully this is more clear and concise now.

I did think about adding data plotters and visualisation but thought there are plenty of packages already available for these purposes and it would help keep the package dependencies slimmer. How about instead of "PyBCI provides an end-to-end solution for BCI research." "PyBCI accelerates the pace of BCI research by streamlining data collection, processing, and model analysis."?

For the latter half of the second point, they don't necessarily need any software skills to integrate, if they have an automated lsl marker delivery from something like Psychopy, a pre-built data viewer like the one from brainvision or eeglab, an off the shelf device with an lsl port it's possible to get the classification right from pycbi in a command prompt. My thought process being someone from the psychology field will have more chance at getting something up and running then trying to write it from scratch. Do you think i should redact this statement? " It provides researchers with the tools necessary to conduct advanced BCI experiments without requiring extensive software development skills. "

**Comment by jsheunis** [comment]
> I think the point i was trying to get at is that it can be integrated in to larger python projects, but i feel its a non sequitur for where i've placed it - Hopefully this is more clear and concise now.

Yup 👍 

> I did think about adding data plotters and visualisation but thought there are plenty of packages already available for these purposes and it would help keep the package dependencies slimmer. How about instead of "PyBCI provides an end-to-end solution for BCI research." "PyBCI accelerates the pace of BCI research by streamlining data collection, processing, and model analysis."?

Sounds good to me.

> For the latter half of the second point, they don't necessarily need any software skills to integrate, if they have an automated lsl marker delivery from something like Psychopy, a pre-built data viewer like the one from brainvision or eeglab, an off the shelf device with an lsl port it's possible to get the classification right from pycbi in a command prompt. My thought process being someone from the psychology field will have more chance at getting something up and running then trying to write it from scratch. Do you think i should redact this statement? " It provides researchers with the tools necessary to conduct advanced BCI experiments without requiring extensive software development skills. "

Thanks for the clarification. I don't think you have to redact, but perhaps you could work the example you just gave into the text to illustrate the point you are trying to make?

**Comment by LMBooth** [comment]
Hi @jsheunis, had another re-jig, hopefully this is fine and I'll close for now, do re-open and comment if you notice any issues.

"By providing a comprehensive, open-source platform for BCI research, PyBCI aims to advance the field. When integrated with off-the-shelf devices that are LSL-enabled, as well as with pre-built LSL data viewers and marker delivery systems, PyBCI facilitates the efficient design, testing, and implementation of advanced BCI experiments. The integration of LSL, PyTorch, Scikit-learn, TensorFlow, Antropy, NumPy, and SciPy into one platform simplifies the research process, encouraging innovation and collaboration in the field of brain computer/human machine interfaces."
